// app/layout.tsx

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SocialMedia from "@/components/SocialMedia"
import "./globals.css";

// Modern Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata
export const metadata: Metadata = {
  title: "Synclink Technologies – IT Services & Consultancy",
  description: "Generated by create next app",
  icons: {
    icon: "/images/smalllogo.png",
  },
};

// RootLayout Component
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header />   {/* Header is client component */}
        <SocialMedia />
        {children}
        <Footer />   {/* Footer can be client component */}
      </body>
    </html>
  );
}
